# A github workflow that validates all json files against their schema
name: Check Hashes
on: [pull_request]

jobs:
  checkhashes:
    name: Check hashes
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Check Source hashes of changed extensions
      run: npm run check-hashes ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }}
